name: Run Deployment Pipeline
on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install modules
        run: yarn
      - name: Build production
        run: yarn build
      - name: Push to github.io
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: "public"
          destination-github-username: "kevelopment"
          destination-repository-name: "kevelopment.github.io"
          user-email: info@kevelopment.dev
          target-branch: "main"
